import Link from "next/link";
import { services } from "./data";
import { Arrow } from "./ui/icons";
import { ParticleWave } from "./ui/particle-wave";
import { HomeLanding } from "./ui/home-landing";
import { HomeEnquiry } from "./ui/home-enquiry";
export default function Home() { return <><HomeLanding/><section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">A new technology studio</p><h1><span className="hero-title-line">Good ideas deserve a</span><span className="hero-title-line"><em>thoughtful beginning.</em></span></h1><p className="lead">VERITRIX is a new studio for thoughtful ideas and real-world problems. We listen closely, build carefully, and create technology that feels right for the people who use it.</p></div><ParticleWave/><div className="hero-invitation"><p>Ready to <em>begin</em> your journey?</p><Link className="button" href="/contact">Start with a conversation <Arrow/></Link></div></section>
<section className="intro about-preview" id="about"><h2>What should good technology feel like?</h2><div className="about-preview-copy"><p className="about-preview-lead">It should make things clearer—not more complicated.</p><p>VERITRIX is a new technology studio bringing thoughtful design and careful engineering together. We create websites, software, mobile applications, digital products and practical automation for businesses with real problems to solve.</p><p>Because we are still at the beginning of our own journey, we value honest conversations, considered decisions and work that has a clear purpose. We take the time to understand what people genuinely need before deciding what should be built.</p><p>We are shaping our studio around close collaboration and steady, transparent progress. That means explaining our thinking, listening throughout the process and building with the longer term in mind.</p><p>Our aim is simple: to create technology that feels useful, understandable and right for the people using it.</p></div><p className="about-preview-invitation">Curious about the thinking behind VERITRIX?</p><Link className="about-preview-link" href="/about">Know more about us <Arrow/></Link><p className="about-preview-closing">Your next chapter is waiting. Let’s build it.</p></section>
<section className="section services-preview" id="services"><div className="section-title"><h2>Services we provide.</h2></div><div className="service-grid">{services.map(([,name,copy])=><Link className="service-card" key={name} href="/services" aria-label={`Learn about ${name}`}><h3>{name}</h3><p>{copy}</p><i><Arrow/></i></Link>)}</div></section>
<section className="section tone why-section"><div className="why-visual" aria-hidden="true"/><div className="why-layout"><div className="why-heading"><p className="eyebrow">Why VERITRIX</p><h2>Where thoughtful technology takes shape.</h2></div><div className="why-principles"><article><div><h3>Clarity First</h3><p className="why-summary">We make decisions, progress and timelines clear from the beginning—without unnecessary jargon or guesswork.</p><p>Technology should not feel like a black box. We explain our thinking, communicate progress honestly and make sure you understand what is being built and why. You should always know where the work stands and what comes next.</p></div></article><article><div><h3>Purpose Over Noise</h3><p className="why-summary">Every feature should have a reason to exist and a real person it helps.</p><p>Instead of chasing trends or adding complexity for its own sake, we begin with the problem. We look closely at how people work, where friction exists and what would genuinely make things easier—then focus on building what matters.</p></div></article><article><div><h3>Built to Evolve</h3><p className="why-summary">Thoughtful foundations should leave room for your organisation to change and grow.</p><p>We approach technology with the longer term in mind. That means creating considered, maintainable foundations that can adapt as needs become clearer—without forcing every future decision to be made today.</p></div></article></div></div></section>
<HomeEnquiry/></>; }
